---
- name: Playbook with Include
  hosts: all
  become: yes

  vars:
    mytext: "Hello from Alex"

  tasks:
    - name: Ping test
      ping:

    -  include: create_folders.yml
    -  include: create_files.yml mytext="Hello from Alex (variable redefinition)"

