---
- name: Playbook for Variables
  hosts: all
  become: yes

  vars:
    message1: Privet
    message2: World
    secret  : ALJKSDGH;LASDGL;KAHSDGL;KHASDLK

  tasks:

  - name: Print Secret variable
    debug:
      var: secret

  - debug:
      msg: "Secret word: {{ secret }}"

  - debug:
      msg: "Owner of server is -->{{ owner }}<--"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message

  - debug:
      var: ansible_distribution

  - shell: uptime
    register: results

  - debug:
      var: results.stdout

