---
- name: Playbook with Delegation
  hosts: all
  become: yes

  vars:
    mytext: "Hello from Alex"

  tasks:
  - name: Ping test
    ping:

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is File#1
        {{ mytext }}
    delegate_to: linuxX3

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
        This is File#2
        {{ mytext }}
        
  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my servers will come up online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 120 
      timeout: 240 
    delegate_to: 127.0.0.1 # localhost wait for servers online status  

  - name: Get and print servers uptime
    shell: /usr/bin/uptime
    register: result

  - debug:
      var: result.stdout

