---
- name: Ansible error handling
  hosts: all
#  any_errors_fatal: true
  become: yes

  tasks:
  - name: Task#1
    yum: name=falsename state=latest
    ignore_errors: yes

  - name: Task#2
    shell: echo Hello World!
    register: results
    failed_when: "'World' in results.stdout"
    ignore_errors: yes

  - debug:
      var: results  

  - name: Task#3
    shell: echo Hello World!
    register: results
#    failed_when: results.rc == 0

  - debug:
      var: results

  - name: Task#4
    shell: cat /home/ec2-user/myfile.txt
    register: results

  - name: Task#5
    shell: echo Last task message!

